# API key for your website. You can obtain it from gamecms.app/profile/my-website
website-api-key: none

# API key for your server (where commands run). You can obtain it from Integrations > Servers
server-api-key: none

# The interval (in ticks) for checking new commands to execute. 20 ticks = 1 second
commands-scheduler: 1200

# Specify whether to use placeholders provided by PlaceholderAPI.
# Note: PlaceholderAPI plugin must be installed for placeholders to work.
use-placeholders: false

# Log message for fetched commands
log-fetched-commands: true