main: me.gamecms.org.GameCMS
name: GameCMS
authors: [ Wohaho ]
description: Plugin for the platform GameCMS.ORG
website: gamecms.org
version: 2.7.4a

commands:
  gcms:
    aliases: [gamecms, game-cms]
    description: Commands for GameCMS.ORG Plugin
    usage: /gcms <command>
    permission: gamecms.admin
    permission-message: You don't have permission to use this command.

permissions:
  gamecms.admin:
    description: Allow players to have access to all plugin commands.
    default: op
  gamecms.balance.check:
    description: Allow players to check others players balance on your website.
    default: op
  gamecms.balance.add:
    description: Allow players to add balance to a specific player on your website.
    default: op
  gamecms.reload:
    description: Reload the configuration.
    default: op
  gamecms.force:
    description: Execute a forced action.
    default: op
  gamecms.api.key.server:
    description: Set the server API key.
    default: op
  gamecms.api.key.website:
    description: Set the website API key.
    default: op
  gamecms.setscheduler:
    description: Set the commands scheduler.
    default: op
  gamecms.placeholders.toggle:
    description: Toggle placeholders usage.
    default: op