main: me.gamecms.org.GameCMS
name: GameCMS
authors: [ Wohaho ]
description: Execute commands from a site provided by gamecms.org
website: gamecms.org
version: 2.6
commands:
  gcms:
    aliases:
      - gamecms
      - game-cms
    permission: gamecms.admin
    permission-message: You don't have enough permission for this action.